{{- if .Values.podDisruptionBudget }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ template "sidecar-injector.fullname" . }}
  labels:
    {{- include "sidecar-injector.labels" . | nindent 4 }}
spec:
  {{- toYaml .Values.podDisruptionBudget | nindent 2 }}
  selector:
    matchLabels:
      {{- include "sidecar-injector.selectorLabels" . | nindent 6 }}
{{- end }}
